name: Binary Release

on:
  push:
    branches:
      - "master"
    paths:
      - ".version"

env:
  FRAMEWORK_ARTIFACT: "wg-go.xcframework"

jobs:
  publish_binary_release:
    name: Publish binary release
    timeout-minutes: 10
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: passepartoutvpn/action-release-binary-package@v1
        with:
          script: "ci-generate.sh"
          framework: "wg-go.xcframework"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
