name: Binary Release

on:
  push:
    branches:
      - "master"
    paths:
      - ".version"

jobs:
  publish_binary_release:
    name: Publish binary release
    runs-on: macos-14
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - uses: passepartoutvpn/action-release-binary-package@master
        with:
          script: "ci-generate.sh"
          framework: "wg-go.xcframework"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
